version: '3'
services:
  data:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build: .
    volumes:
      - .:/blackjack
    ports:
      - "5000:5000"
    depends_on:
      - data
